#:schema node_modules/wrangler/config-schema.json
name = "clothes-discounts"
main = "./server.ts"
# workers_dev = true

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

compatibility_flags = ["nodejs_compat"]

kv_namespaces = [{ binding = "cache", id = "43a0f0a09e634a62a243019b5d17a62d" }]

# 静的ファイルの置き場
[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

# Deploy前に実行されるコマンド
[build]
command = "npm run build"

# 環境変数の設定
[vars]
GITHUB_OWNER = "edmundhung"
GITHUB_REPO = "remix-cloudflare-template"

[[d1_databases]]
binding = "DATABASE"
database_name = "clothes-discounts"
database_id = "163dec0c-e3ec-4f4a-a974-79b807d7cab4"

[observability]
enabled = true
head_sampling_rate = 1
