name: CI
on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
jobs:
  # テスト未実装のためコメントアウト
  # test:
  #   name: 🔍 Testing
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ⬇️ Checkout repo
  #       uses: actions/checkout@v7
  #     - name: ⎔ Setup node
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 20
  #     - name: 📥 Download deps
  #       uses: bahmutov/npm-install@v1
  #       with:
  #         useLockFile: false
  #     - name: 🎭 Install Playwright
  #       run: npx playwright install --with-deps
  #     - name: 📦 Prepare the environment
  #       run: cp .dev.vars.example .dev.vars
  #     - name: 💣 Run some tests
  #       run: npm run test

  lint:
    name: ⬣ Linting
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7
      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: ✨ Code format check
        run: npm run format -- --check .
      - name: ✅ Code linting
        run: npm run lint
