name: Daily Insert

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  insert-men-discount:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ke-suke0215/discount-scraper:1.0.3
      env:
        REMIX_APP_URL: ${{ secrets.REMIX_APP_URL }}
        INSERT_DISCOUNT_API_KEY: ${{ secrets.INSERT_DISCOUNT_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: exec scraping
        run: python auto-insert/men_scraping.py

  insert-women-discount:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ke-suke0215/discount-scraper:1.0.3
      env:
        REMIX_APP_URL: ${{ secrets.REMIX_APP_URL }}
        INSERT_DISCOUNT_API_KEY: ${{ secrets.INSERT_DISCOUNT_API_KEY }}

    needs: [insert-men-discount]
    if: always()  # menのinsertジョブが失敗しても実行する

    steps:
      - uses: actions/checkout@v2
      - name: exec scraping
        run: python auto-insert/women_scraping.py

  # 各ジョブの実行時間をタイムライン形式で表示する
  draw_timeline:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [insert-men-discount, insert-women-discount]
    if: always()

    steps:
      - uses: Kesin11/actions-timeline@v2
